export const BOOKING_SOURCES = Object.freeze({
  DIRECT: "DIRECT",
  EXPEDIA: "EXPEDIA",
  BOOKING: "BOOKING",
  AIRBNB: "AIRBNB",
  CORPORATE: "CORPORATE",
  WALKIN: "WALKIN",
});

export const BOOKING_SOURCE_LIST = Object.values(BOOKING_SOURCES);
