export const USER_ROLES = Object.freeze({
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  FRONT_DESK: "FRONT_DESK",
  HOUSEKEEPING: "HOUSEKEEPING",
});

export const USER_ROLE_LIST = Object.values(USER_ROLES);

export const ROLE_ACCESS = Object.freeze({
  dashboard:    [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.FRONT_DESK],
  reservations: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.FRONT_DESK],
  frontDesk:    [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.FRONT_DESK],
  housekeeping: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.HOUSEKEEPING],
  ratesYield:   [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  channels:     [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  reports:      [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
  guests:       [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.FRONT_DESK],
  settings:     [USER_ROLES.ADMIN, USER_ROLES.MANAGER],
});
